//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpSim.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpSim.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Setting&gt;
        ///  &lt;Rooms&gt;
        ///    &lt;Room&gt;
        ///      &lt;Id&gt;1&lt;/Id&gt;
        ///      &lt;Name&gt;Your room&lt;/Name&gt;
        ///      &lt;Desc&gt;This is your room&lt;/Desc&gt;
        ///      &lt;Links&gt;2&lt;/Links&gt;
        ///    &lt;/Room&gt;
        ///    &lt;Room&gt;
        ///      &lt;Id&gt;2&lt;/Id&gt;
        ///      &lt;Name&gt;Corridor&lt;/Name&gt;
        ///      &lt;Desc&gt;This is a corridor&lt;/Desc&gt;
        ///      &lt;Links&gt;1,3&lt;/Links&gt;
        ///    &lt;/Room&gt;
        ///    &lt;Room&gt;
        ///      &lt;Id&gt;3&lt;/Id&gt;
        ///      &lt;Name&gt;Another room&lt;/Name&gt;
        ///      &lt;Desc&gt;This is anther room&lt;/Desc&gt;
        ///      &lt;Links&gt;2&lt;/Links&gt;
        ///    &lt;/Room&gt;
        ///  &lt;/Rooms&gt;
        ///&lt;/Setting&gt;.
        /// </summary>
        internal static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
    }
}
